export const snippets = {
  "cx-data-grid": {
    "prefix": "cx-data-grid",
    "body": [
      "<cx-data-grid",
      "  ref=\"${1:grid}\"",
      "  size=\"${2:default}\"",
      "  :no-index=\"${3:false}\"",
      "  :idx-serial=\"${4:false}\"",
      "  :rmenus=\"${5:[]}\"",
      "  :datagrid=\"{",
      "    table: {",
      "      list: ${6:[]},",
      "      cols: [",
      "        {",
      "          colname: '${7:field}',",
      "          title: '${8:标题}',",
      "          align: '${9:center}',",
      "          visible: ${10:1}",
      "        }",
      "      ],",
      "      border: ${11:true},",
      "      stripe: ${12:true},",
      "      highlightCurrentRow: ${13:true}",
      "    },",
      "    pages: ${14:true},",
      "    page: {",
      "      total: ${15:0},",
      "      pageSize: ${16:10},",
      "      pageSizes: ${17:[10, 20, 50, 100]},",
      "      layout: '${18:total, sizes, prev, pager, next, jumper}'",
      "    }",
      "  }\"",
      "  @row-click=\"${19:onRowClick}\"",
      "  @row-dblclick=\"${20:onRowDblclick}\"",
      "  @cell-click=\"${21:onCellClick}\"",
      "  @header-click=\"${22:onHeaderClick}\"",
      "  @current-change=\"${23:onCurrentChange}\"",
      "  @selection-change=\"${24:onSelectionChange}\"",
      "  @sort-change=\"${25:onSortChange}\"",
      "  @cell-mouse-enter=\"${26:onCellMouseEnter}\"",
      "  @cell-mouse-leave=\"${27:onCellMouseLeave}\"",
      "  @plugin-click=\"${28:onPluginClick}\"",
      "  @edit-row=\"${29:onEditRow}\"",
      "  @key-enter=\"${30:onKeyEnter}\"",
      "  @load-more=\"${31:onLoadMore}\"",
      "  @row-contextmenu=\"${32:onRowContextmenu}\"",
      "  @pagesize-change=\"${33:onPagesizeChange}\"",
      "  @page-change=\"${34:onPageChange}\"",
      ">",
      "  ${35:<!-- 内容部分 -->}",
      "</cx-data-grid>"
    ],
    "description": "数据网格"
  }
}; 