export const snippets = {
  "cx-chart-pie-2d": {
    "prefix": "cx-chart-pie-2d",
    "body": [
      "<cx-chart-pie-2d",
      "  :data=\"${1:[",
      "    { name: '类目1', value: 100 },",
      "    { name: '类目2', value: 200 },",
      "    { name: '类目3', value: 300 }",
      "  ]}\"",
      "  :config=\"${2:{",
      "    tooltip: {",
      "      trigger: 'item',",
      "      show: true",
      "    },",
      "    legend: {",
      "      type: 'plain',",
      "      show: true,",
      "      orient: 'horizontal',",
      "      left: 'center',",
      "      top: 'bottom'",
      "    },",
      "    series: {",
      "      center: ['50%', '50%'],",
      "      radius: ['0%', '75%'],",
      "      label: {",
      "        show: true,",
      "        position: 'outside'",
      "      },",
      "      labelLine: {",
      "        show: true,",
      "        length: 10,",
      "        length2: 10",
      "      }",
      "    }",
      "  }}\"",
      "  :colors=\"${3:['blue', 'green', 'red']}\"",
      "  @click=\"${4:handleClick}\"",
      "  @dblclick=\"${5:handleDblClick}\"",
      "  @mousedown=\"${6:handleMouseDown}\"",
      "  @mousemove=\"${7:handleMouseMove}\"",
      "  @mouseup=\"${8:handleMouseUp}\"",
      "  @mouseover=\"${9:handleMouseOver}\"",
      "  @mouseout=\"${10:handleMouseOut}\"",
      "/>"
    ],
    "description": "2D饼图组件，支持自定义配置和事件处理"
  }
}; 