export const snippets = {
  "cx-chart-bar-and-line": {
    "prefix": "cx-chart-bar-and-line",
    "body": [
      "<cx-chart-bar-and-line",
      "  :data=\"${1:[",
      "    {",
      "      values: [100, 200, 300],",
      "      axises: ['类目1', '类目2', '类目3']",
      "    }",
      "  ]}\"",
      "  :config=\"${2:{",
      "    grid: {",
      "      show: false,",
      "      left: '5%',",
      "      right: '5%',",
      "      top: '10%',",
      "      bottom: '10%'",
      "    },",
      "    tooltip: {",
      "      trigger: 'axis',",
      "      show: true",
      "    },",
      "    xAxis: {",
      "      type: 'category',",
      "      boundaryGap: true",
      "    },",
      "    yAxis: {",
      "      type: 'value'",
      "    },",
      "    series: [",
      "      {",
      "        type: 'bar',",
      "        barWidth: 20",
      "      },",
      "      {",
      "        type: 'line',",
      "        smooth: true",
      "      }",
      "    ]",
      "  }}\"",
      "  :colors=\"${3:['blue', 'green', 'red']}\"",
      "/>"
    ],
    "description": "柱状折线图组件，支持柱状图和折线图的组合展示"
  }
}; 