export const snippets = {
  "cx-files-man": {
    "prefix": "cx-files-man",
    "body": [
      "<cx-files-man",
      "  :size=\"'default'\"",
      "  :tree-com=\"'cx-dirs-tree'\"",
      "  :dirs=\"[",
      "    {",
      "      dir: '',",
      "      params: {",
      "        rootLabel: '',",
      "        authDir: {",
      "          addable: true,",
      "          editable: true,",
      "          removable: true",
      "        },",
      "        authFile: {",
      "          downloadable: true,",
      "          uploadable: true,",
      "          editable: true,",
      "          removable: true,",
      "          sharable: true",
      "        }",
      "      }",
      "    }",
      "  ]\"",
      "  :tree-plug=\"'FileDir'\"",
      "  :root-label=\"''\"",
      "  :draggable=\"false\"",
      "  :tree-values=\"cx.dc.FileDirValues\"",
      "  :tree-handler=\"new cx.dc.DirsTreeHandler()\"",
      "  :tree-attrs=\"{ selectFirst: true, expandRoot: true }\"",
      "  :file-plugs=\"'File'\"",
      "  :file-exp-values=\"cx.dc.FileValues\"",
      "  :list-type=\"'list'\"",
      "  :file-card-com=\"'cx-file-card'\"",
      "  @set-data=\"(data, file) => {}\"",
      "  @after-upload=\"(ret) => {}\"",
      ">",
      "  <template #dirtree-default=\"{ data }\">",
      "    <!-- 目录树-插槽 -->",
      "  </template>",
      "  <template #dirfile-preappend>",
      "    <!-- 目录文件组件-操作按钮之前 -->",
      "  </template>",
      "  <template #dirfile-append>",
      "    <!-- 目录文件组件-操作按钮之后 -->",
      "  </template>",
      "</cx-files-man>"
    ],
    "description": "多目录文件管理组件"
  }
};

export default snippets; 