export const snippets = {
  "cx-tool-bar": {
    "prefix": "cx-tool-bar",
    "body": [
      "<cx-tool-bar",
      "  :tools=\"[",
      "    [",
      "      {",
      "        name: '${1:tool1}',",
      "        title: '${2:工具1}',",
      "        namec: '${3:工具1}',",
      "        icon: '${4:cx-fi ic-tool1}',",
      "        plugin: '${5:plugin1}',",
      "        params: {}",
      "      },",
      "      {",
      "        name: '${6:tool2}',",
      "        title: '${7:工具2}',",
      "        namec: '${8:工具2}',",
      "        icon: '${9:cx-fi ic-tool2}',",
      "        children: [",
      "          {",
      "            name: '${10:subtool1}',",
      "            title: '${11:子工具1}',",
      "            namec: '${12:子工具1}',",
      "            icon: '${13:cx-fi ic-subtool1}',",
      "            plugin: '${14:subplugin1}',",
      "            params: {}",
      "          }",
      "        ]",
      "      }",
      "    ]",
      "  ]\"",
      "  mode=\"${15:horizontal}\"",
      "  subToolMode=\"${16:horizontal}\"",
      "  subToolPlace=\"${17:bottom}\"",
      "  @tool-click=\"${18:onToolClick}\"",
      "  @tool-active=\"${19:onToolActive}\"",
      "  @tool-inactive=\"${20:onToolInactive}\"",
      "/>"
    ],
    "description": "工具条"
  }
}; 