export const snippets = {
  "cx-dialog": {
    "prefix": "cx-dialog",
    "body": [
      "<cx-dialog",
      "  :size=\"${1:'default'}\"",
      "  :active=\"${2:false}\"",
      "  :dlg=\"${3:{",
      "    name: '${4:对话框名称}',",
      "    title: '${5:对话框标题}',",
      "    width: '${6:500px}',",
      "    height: '${7:300px}',",
      "    pos: {",
      "      left: '${8:auto}',",
      "      top: '${9:auto}'",
      "    },",
      "    icon: '${10:}',",
      "    modal: ${11:false},",
      "    closable: ${12:true},",
      "    foldable: ${13:false},",
      "    minable: ${14:false},",
      "    maxable: ${15:false},",
      "    movable: ${16:true},",
      "    resizeable: ${17:true},",
      "    borderCom: '${18:cx-border-regular}',",
      "    headerCom: '${19:cx-header-card}',",
      "    minTitle: '${20:}',",
      "    minTitleStyle: '${21:}',",
      "    minIcon: '${22:}',",
      "    minIconStyle: '${23:}'",
      "  }}\"",
      "  :border=\"${24:{}}\"",
      "  :header=\"${25:{}}\"",
      "  :content=\"${26:{}}\"",
      "  @min-change=\"${27:onMinChange}\"",
      "  @max-change=\"${28:onMaxChange}\"",
      "  @close=\"${29:onClose}\"",
      "  @dlg-active=\"${30:onActive}\"",
      ">",
      "  <template #header-preappend>${31:<!-- 标题之前 -->}</template>",
      "  <template #header-title>${32:<!-- 标题附加 -->}</template>",
      "  <template #header-append>${33:<!-- 标题之后 -->}</template>",
      "  <template #min-title>${34:<!-- 最小化时的面板内容 -->}</template>",
      "  ${35:内容}",
      "</cx-dialog>"
    ],
    "description": "对话框组件，支持拖拽、缩放、最小化、最大化等功能"
  }
}; 