export const snippets = {
  "cx-grid-table": {
    "prefix": "cx-grid-table",
    "body": [
      "<cx-grid-table",
      "  ref=\"${1:table}\"",
      "  size=\"${2:default}\"",
      "  :table=\"{",
      "    list: ${3:[]},",
      "    cols: [",
      "      {",
      "        colname: '${4:field}',",
      "        title: '${5:标题}',",
      "        align: '${6:center}',",
      "        width: ${7:100},",
      "        sortable: ${8:false},",
      "        overflowTooltip: ${9:false},",
      "        isEdit: ${10:false},",
      "        isCheckBox: ${11:false},",
      "        isSwitch: ${12:false},",
      "        isSelect: ${13:false},",
      "        isCascader: ${14:false},",
      "        isDate: ${15:false},",
      "        isDateTime: ${16:false},",
      "        isHtml: ${17:false}",
      "      }",
      "    ],",
      "    operCols: [",
      "      {",
      "        colname: '${18:operation}',",
      "        title: '${19:操作}',",
      "        btns: ${20:[]},",
      "        width: ${21:100},",
      "        max: ${22:3},",
      "        align: '${23:center}'",
      "      }",
      "    ],",
      "    operFix: '${24:right}',",
      "    multiple: ${25:false},",
      "    dbClickEdit: ${26:false},",
      "    selectOnClick: ${27:true},",
      "    fitWidth: ${28:false},",
      "    addable: ${29:false},",
      "    elAtts: ${30:{}},",
      "    elEvts: ${31:{}}",
      "  }\"",
      "  :no-index=\"${32:false}\"",
      "  :index-el-atts=\"${33:{}}\"",
      "  :index-func=\"${34:indexFunc}\"",
      "  @row-click=\"${35:onRowClick}\"",
      "  @row-dblclick=\"${36:onRowDblclick}\"",
      "  @cell-click=\"${37:onCellClick}\"",
      "  @header-click=\"${38:onHeaderClick}\"",
      "  @selection-change=\"${39:onSelectionChange}\"",
      "  @sort-change=\"${40:onSortChange}\"",
      "  @cell-mouse-enter=\"${41:onCellMouseEnter}\"",
      "  @cell-mouse-leave=\"${42:onCellMouseLeave}\"",
      "  @plugin-click=\"${43:onPluginClick}\"",
      "  @edit-row=\"${44:onEditRow}\"",
      "  @key-enter=\"${45:onKeyEnter}\"",
      "  @load-more=\"${46:onLoadMore}\"",
      "  @row-contextmenu=\"${47:onRowContextmenu}\"",
      "  @change-select=\"${48:onChangeSelect}\"",
      "  @change-check=\"${49:onChangeCheck}\"",
      "  @change-switch=\"${50:onChangeSwitch}\"",
      "  @visible-change=\"${51:onVisibleChange}\"",
      "/>"
    ],
    "description": "网格表"
  }
}; 